'use strict';
const assert = require('assert');
const { createSignedReferralIdentifier, createMiniAppReferralLink, referralIdentifierQuery } = require('../utils/referralCore');

const secret = 'referral-test-secret';
const telegramId = '8977745850';
const signed = createSignedReferralIdentifier(telegramId, secret);
assert.match(signed, /^8977745850_[a-f0-9]{24}$/);
assert.deepStrictEqual(referralIdentifierQuery(signed, secret), { telegramId });
assert.deepStrictEqual(referralIdentifierQuery(`ref_${signed}`, secret), { telegramId });
const referralLink = createMiniAppReferralLink('Gram_up_bot', '8351243288');
assert.strictEqual(referralLink, 'https://t.me/Gram_up_bot?start=8351243288');
assert.strictEqual(createMiniAppReferralLink('@Gram_up_bot', '8351243288'), 'https://t.me/Gram_up_bot?start=8351243288');
const startPayload = new URL(referralLink).searchParams.get('start');
assert.strictEqual(new URL(referralLink).searchParams.has('startapp'), false, 'referral link starts the bot rather than bypassing to Mini App');
assert.deepStrictEqual(referralIdentifierQuery(startPayload, secret), { telegramId: '8351243288' }, 'start payload resolves to the inviter');
assert.strictEqual(createMiniAppReferralLink('invalid bot', '8351243288'), '');
assert.strictEqual(createMiniAppReferralLink('Gram_up_bot', 'not-a-telegram-id'), '');
assert.deepStrictEqual(referralIdentifierQuery('8977745850', secret), { telegramId: '8977745850' }, 'numeric start payload IDs resolve to Telegram users');
assert.deepStrictEqual(referralIdentifierQuery('ref_8977745850', secret), { telegramId: '8977745850' }, 'numeric IDs keep the legacy ref_ prefix compatibility');
assert.strictEqual(referralIdentifierQuery(signed.replace(/^\d+/, '8977745851'), secret), null, 'changing the Telegram ID invalidates its signature');
assert.strictEqual(referralIdentifierQuery(signed, 'different-secret'), null, 'signatures are server-secret-specific');
assert.deepStrictEqual(referralIdentifierQuery('r123abc9'), { referralCode: 'R123ABC9' });
assert.deepStrictEqual(referralIdentifierQuery('ref_r123abc9'), { referralCode: 'R123ABC9' });
assert.strictEqual(referralIdentifierQuery(''), null);
assert.strictEqual(referralIdentifierQuery('$where'), null);
assert.strictEqual(referralIdentifierQuery('bad-id with spaces'), null);
console.log('ALL PASS — signed Telegram-ID referral links and legacy codes');
